### ISSUE TITLE
Linker error: ld: file not found: /..../Project/ios/build/libs/ios/libObjectAL.a

### ISSUE THREAD

**Issue by AgrarPirat** [robovm/robovm-idea#48]
Hello roboVM Team,

I'm running into linker errors when trying to create an IPA. The project setup is:
roboVM 1.1.0, 
libGDX 1.5.5
android.tools.build:gradle:1.1.2
org.robovm:robovm-gradle-plugin:1.1.0
org.robovm.idea-1.1.1-SNAPSHOT-plugin-dist-20150422_021132-51

Below is the error output. Do you have any ideas how to fix or workaround it, in a way that leads to a valid .ipa output?
Thank you.

```
[DEBUG] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/usr/Library/Caches/AndroidStudio/tmp/robovm7571209546049977807.tmp/thumbv7/IOSLauncher -arch armv7 -Wl,-filelist,/Users/usr/Library/Caches/AndroidStudio/tmp/robovm7571209546049977807.tmp/thumbv7/objects -L /Users/usr/.robovm-sdks/robovm-1.1.1-SNAPSHOT/lib/vm/ios/thumbv7 -ObjC -exported_symbols_list /Users/usr/Library/Caches/AndroidStudio/tmp/robovm7571209546049977807.tmp/thumbv7/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/usr/.robovm/cache/ios/thumbv7/release/Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/libs/facebook-1.0.0.jar.extracted/META-INF/robovm/ios/libs -miphoneos-version-min=5.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk -lrobovm-bc -force_load /Users/usr/.robovm-sdks/robovm-1.1.1-SNAPSHOT/lib/vm/ios/thumbv7/librobovm-rt.a -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -framework Foundation -framework StoreKit -framework CoreData -framework SystemConfiguration -framework FacebookSDK -framework CoreLocation -framework CoreGraphics -framework UIKit -framework OpenGLES -framework QuartzCore -framework OpenAL -framework AudioToolbox -framework AVFoundation -force_load /Users/usr/.robovm/cache/ios/thumbv7/release/Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/libs/google-analytics-1.0.0.jar.extracted/META-INF/robovm/ios/libs/libgoogleanalytics.a -force_load /Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/build/libs/ios/libObjectAL.a -force_load /Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/build/libs/ios/libgdx-freetype.a -force_load /Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/build/libs/ios/libgdx.a -framework MobileCoreServices
[ERROR] ld: file not found: /Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/build/libs/ios/libObjectAL.a
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't create IPA
org.apache.commons.exec.ExecuteException: Command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/usr/Library/Caches/AndroidStudio/tmp/robovm7571209546049977807.tmp/thumbv7/IOSLauncher -arch armv7 -Wl,-filelist,/Users/usr/Library/Caches/AndroidStudio/tmp/robovm7571209546049977807.tmp/thumbv7/objects -L /Users/usr/.robovm-sdks/robovm-1.1.1-SNAPSHOT/lib/vm/ios/thumbv7 -ObjC -exported_symbols_list /Users/usr/Library/Caches/AndroidStudio/tmp/robovm7571209546049977807.tmp/thumbv7/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/usr/.robovm/cache/ios/thumbv7/release/Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/libs/facebook-1.0.0.jar.extracted/META-INF/robovm/ios/libs -miphoneos-version-min=5.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk -lrobovm-bc -force_load /Users/usr/.robovm-sdks/robovm-1.1.1-SNAPSHOT/lib/vm/ios/thumbv7/librobovm-rt.a -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -framework Foundation -framework StoreKit -framework CoreData -framework SystemConfiguration -framework FacebookSDK -framework CoreLocation -framework CoreGraphics -framework UIKit -framework OpenGLES -framework QuartzCore -framework OpenAL -framework AudioToolbox -framework AVFoundation -force_load /Users/usr/.robovm/cache/ios/thumbv7/release/Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/libs/google-analytics-1.0.0.jar.extracted/META-INF/robovm/ios/libs/libgoogleanalytics.a -force_load /Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/build/libs/ios/libObjectAL.a -force_load /Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/build/libs/ios/libgdx-freetype.a -force_load /Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/build/libs/ios/libgdx.a -framework MobileCoreServices' failed (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
    at org.robovm.compiler.util.Executor.exec(Executor.java:344)
    at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:300)
    at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:206)
    at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:314)
    at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:200)
    at org.robovm.compiler.Linker.link(Linker.java:359)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:389)
    at org.robovm.compiler.AppCompiler.createIpa(AppCompiler.java:683)
    at org.robovm.idea.compilation.RoboVmCompileTask$1.doCompile(RoboVmCompileTask.java:110)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)

[INFO] IPA creation complete, 0 errors, 0 warnings
```

**Comment by badlogic** [comment]
Does this file exist: `/Users/usr/Workspace/AndroidStudio/MyAwesomeProject/ios/build/libs/ios/libObjectAL.a`?

**Comment by AgrarPirat** [comment]
Thanks for the quick reply. Yes, the file is actually there.
Is there a workaround to create an .IPA file? I've tried "./gradlew createIPA", which is working well, except that it uses the development code signing identity instead of the distribution code signing identity. Is there a way to change this?

**Comment by badlogic** [comment]
Please update to RoboVM 1.2 and libGDX 1.6.0 (IDE plugin and build.gradle file!). I couldn't reproduce this issue with the current and previous versions.

Regarding signing identity, check out the usage docs for the RoboVM Gradle plugin: https://github.com/robovm/robovm-gradle-plugin you can specify it in a robovm closure in build.gradle.

I'll reopen this if the issue still persists.
