### ISSUE TITLE
NullPointerException on launch

### ISSUE THREAD

**Issue by fechy** [robovm/robovm-idea#62]
When trying to debug using a simulator from IntelliJ, I get this error every time:

```
[ERROR] Couldn't compile app
java.lang.NullPointerException
    at java.io.File.<init>(File.java:277)
    at org.robovm.idea.compilation.RoboVmCompileTask.configureClassAndSourcepaths(RoboVmCompileTask.java:260)
    at org.robovm.idea.compilation.RoboVmCompileTask.compileForRunConfiguration(RoboVmCompileTask.java:189)
    at org.robovm.idea.compilation.RoboVmCompileTask.execute(RoboVmCompileTask.java:75)
    at com.intellij.compiler.impl.CompileDriver.executeCompileTasks(CompileDriver.java:627)
    at com.intellij.compiler.impl.CompileDriver.access$400(CompileDriver.java:88)
    at com.intellij.compiler.impl.CompileDriver$3.run(CompileDriver.java:410)
    at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:203)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

Running the gradle command directly, it works.

I'm in a Mac, with IntelliJ 14.1.3.
I have tried also updating the Robovm plugin to the latest nightly but it still doesn't run. I have tried all the options in the Run/Debug configurations but nothing seems to work.

**Comment by badlogic** [comment]
Can you describe the project you are trying to compile?

**Comment by badlogic** [comment]
Also, is the stack trace from the nightly or release build?

**Comment by fechy** [comment]
The project is an almost barebones Libgdx project. With spine and a version of SQLite plugin (https://github.com/mrafayaleem/gdx-sqlite).
The project throws a catched exception which is only visible running on the command line. However the projects keeps on going.
On IntelliJ it doesn't even starts.

Both release and nightly have the same stacktrace.

**Comment by badlogic** [comment]
Just commited a fix for this. The nightly is building and should be ready in 10 minutes from now. Please give it a try, recompile your project, and post the logs from the RoboVM console in IDEA here. You should find a string like "Output path of module XXX not defined". Would be interested to know what module in a standard libGDX setup is acting up.

**Comment by badlogic** [comment]
Sorry, had to trigger another build. Give it 15 minutes, then use the nightly with the newest timestamp :)

**Comment by fechy** [comment]
Ok, I get:

```
[WARNING] Output path of module arkanoid not defined
```

Where arkanoid is the name of my project.

Besides adding my own projects and updated the versions, the gradle.build file stays untouch from what LibGdx setup creates.

**Comment by badlogic** [comment]
Hm, i guess that's the parent "module" that Gradle generates. I assume compilation works now for you?

**Comment by fechy** [comment]
Yes, and no. But I can't blame Robovm for this (Or maybe I do):

```
[ERROR] Couldn't compile app
org.robovm.compiler.CompilerException: Root class org.sqlite.JDBC not found
    at org.robovm.compiler.AppCompiler.getRootClasses(AppCompiler.java:219)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:374)
    at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
```

Either way, it's way better and from now on it's my problem.
Unless you know how to solve the above... :+1: 

Just joking. Thanks for fixing it.

**Comment by badlogic** [comment]
If you can create a sample project with your Gradle setup i can take a look. I assume it has to do with this issue here actually, as the dependencies of the parent project aren't properly pulled in now in your case.

**Comment by fechy** [comment]
I have just put a simple (an kinda messy) test here: https://github.com/fechy/gdx-sqlite-test
Now, in this test, running launchIphoneSimulator on the command line everything seems to works as expected. From IntelliJ, it just doesn't run and gives the above mentioned issue.

**Comment by badlogic** [comment]
Great, I'll look into it!

**Comment by badlogic** [comment]
I believe i have resolved this issue. I triggered a build of the latest IDEA plugin snapshot, should be available in 30 minutes from now.

I successfully import and build your test project. Here's the output in the RoboVM Console (minus the lines for each compiled class).

```
[DEBUG] Loading default RoboVM config properties file: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm.properties
[DEBUG] Loading default RoboVM config file: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm.xml
[INFO] Building executable in /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86
[INFO] Installation of app in /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/core/build/classes/main
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/gdx-sqlite-desktop/build/classes/main
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/gdx-sqlite-robovm/build/resources/main
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/desktop/build/classes/main
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.2/d276cdf61fe2b516c7b7f4aa1b8dea91dbdc8d56/lwjgl-platform-2.9.2-natives-linux.jar
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput-platform/2.0.5/7ff832a6eb9ab6a767f1ade2b548092d0fa64795/jinput-platform-2.0.5-natives-linux.jar
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/gdx-sqlite-robovm/build/classes/main
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.6.0/276722e4fa28b31548cbca11c382af1c4e0cf690/gdx-platform-1.6.0-natives-desktop.jar
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.2/510c7d317f5e9e700b9cfaac5fd38bdebf0702e0/lwjgl-platform-2.9.2-natives-windows.jar
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/android/build/intermediates/classes/debug
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/classes/production/gdx-sqlite-test
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl_util/2.9.2/4b9e37300a87799856e0bd15ed81663cdb6b0947/lwjgl_util-2.9.2.jar
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/gdx-sqlite-android/build/intermediates/classes/debug
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.6.0/b7ac8e495b4e4828a30fa97654a17bdfb9f93734/gdx-1.6.0.jar
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/build/classes/main
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-lwjgl/1.6.0/442f452a2e78c2e67be9c91138c279044617dd48/gdx-backend-lwjgl-1.6.0.jar
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-box2d/1.6.0/66c0d9d2edb567e95fae97c03e79fe753fcd18e0/gdx-box2d-1.6.0.jar
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/gdx-sqlite-robovm/libs/sqlite-jdbc-3.7.2.jar
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/gdx-sqlite/build/resources/main
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput-platform/2.0.5/385ee093e01f587f30ee1c8a2ee7d408fd732e16/jinput-platform-2.0.5-natives-windows.jar
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/org.jcraft/jorbis/0.0.17/8872d22b293e8f5d7d56ff92be966e6dc28ebdc6/jorbis-0.0.17.jar
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-freetype-platform/1.6.0/366a7efa22d863348696af542a1b02dd67a8165d/gdx-freetype-platform-1.6.0-natives-desktop.jar
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/gdx-sqlite/build/classes/main
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput/2.0.5/39c7796b469a600f72380316f6b1f11db6c2c7c4/jinput-2.0.5.jar
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/com.badlogicgames.jlayer/jlayer/1.0.1-gdx/7cca83cec5c1b2f011362f4d85aabd71a73b049d/jlayer-1.0.1-gdx.jar
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/core/build/resources/main
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput-platform/2.0.5/53f9c919f34d2ca9de8c51fc4e1e8282029a9232/jinput-platform-2.0.5-natives-osx.jar
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.2/d55b46b40b40249d627a83a7f7f22649709d70c3/lwjgl-platform-2.9.2-natives-osx.jar
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.2/a9d80fe5935c7a9149f6584d9777cfd471f65489/lwjgl-2.9.2.jar
[INFO] classpath entry: /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/build/resources/main
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/net.java.jutils/jutils/1.0.0/e12fe1fda814bd348c1579329c86943d2cd3c6a6/jutils-1.0.0.jar
[INFO] classpath entry: /Users/badlogic/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-robovm/1.6.0/2e62b8efb00b5563778291599cd7b2c12edba777/gdx-backend-robovm-1.6.0.jar
[INFO] Using SDK boot classpath
[INFO] Cleaning output dir /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86
[WARNING] Classpath entry /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/classes/production/gdx-sqlite-test does not exist
[DEBUG] Compiling classes using 8 threads
[DEBUG] Compiled 0 classes in 3.90 seconds
[INFO] Linking 4102 classes (ios x86 release)
[DEBUG] Building executable /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher
[DEBUG] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher -arch i386 -Wl,-filelist,/Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/objects -L /Users/badlogic/.robovm-sdks/robovm-1.2.1-SNAPSHOT/lib/vm/ios/x86 -ObjC -exported_symbols_list /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -mios-simulator-version-min=5.0 -Wl,-no_pie -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -lrobovm-bc -force_load /Users/badlogic/.robovm-sdks/robovm-1.2.1-SNAPSHOT/lib/vm/ios/x86/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -framework UIKit -framework OpenGLES -framework QuartzCore -framework CoreGraphics -framework OpenAL -framework AudioToolbox -framework AVFoundation -force_load /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/build/libs/ios/libgdx-box2d.a -force_load /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/build/libs/ios/libgdx.a -force_load /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/build/libs/ios/libObjectAL.a -framework MobileCoreServices
[DEBUG] Linked 4102 classes in 4.35 seconds
[INFO] Build done
[INFO] Launching executable
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/boot/robovm-rt.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/boot/robovm-rt-sources.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/classes0.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/classes1.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/classes2.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/lwjgl-platform-2.9.2-natives-linux.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/jinput-platform-2.0.5-natives-linux.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/classes5.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/gdx-platform-1.6.0-natives-desktop.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/lwjgl-platform-2.9.2-natives-windows.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/classes8.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/lwjgl_util-2.9.2.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/classes10.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/gdx-1.6.0.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/classes12.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/gdx-backend-lwjgl-1.6.0.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/gdx-box2d-1.6.0.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/sqlite-jdbc-3.7.2.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/jinput-platform-2.0.5-natives-windows.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/jorbis-0.0.17.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/gdx-freetype-platform-1.6.0-natives-desktop.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/classes19.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/jinput-2.0.5.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/jlayer-1.0.1-gdx.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/jinput-platform-2.0.5-natives-osx.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/lwjgl-platform-2.9.2-natives-osx.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/lwjgl-2.9.2.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/jutils-1.0.0.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/gdx-backend-robovm-1.6.0.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/robovm-cacerts-full.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/robovm-cocoatouch-sources.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/robovm-cocoatouch.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/robovm-objc-sources.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/robovm-objc.jar
[DEBUG] Creating stripped archive file /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/lib/boot/robovm-cacerts-full.jar
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/android/assets/badlogic.jpg to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/android/assets/test.db to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Default-375w-667h@2x.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Default-414w-736h@3x.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Default-568h@2x.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Default.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Default@2x.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Default@2x~ipad.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Default~ipad.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Icon-72.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Icon-72@2x.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Icon.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Copying resource /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/data/Icon@2x.png to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] Installing Info.plist to /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app
[DEBUG] xcrun dsymutil -o /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app.dSYM /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app/IOSLauncher
[DEBUG] /Users/badlogic/.robovm-sdks/robovm-1.2.1-SNAPSHOT/bin/ios-sim launch /Users/badlogic/workspaces/robovm-test/gdx-sqlite-test/ios/robovm-build/tmp/Unnamed/ios/x86/IOSLauncher.app --timeout 90 --unbuffered --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 8.3" --stdout /Users/badlogic/Library/Caches/IdeaIC14/plugins-sandbox/system/tmp/robovm-stdout-6794578662643662550.fifo --stderr /Users/badlogic/Library/Caches/IdeaIC14/plugins-sandbox/system/tmp/robovm-stderr-8317875128848501422.fifo --setenv ROBOVM_LAUNCH_MODE=release --args -rvm:log=warn
[INFO] Launch done
```

Here's the output of the app on the simulator:

```
2015-05-18 13:41:33.399 IOSLauncher[3958:116515] [debug] IOSApplication: iOS version: 8.3
2015-05-18 13:41:33.400 IOSLauncher[3958:116515] [debug] IOSApplication: Running in 32-bit mode
2015-05-18 13:41:33.401 IOSLauncher[3958:116515] [debug] IOSApplication: scale: 2.0
2015-05-18 13:41:33.405 IOSLauncher[3958:116515] [debug] IOSApplication: Unscaled View: Portrait 320x480
2015-05-18 13:41:33.405 IOSLauncher[3958:116515] [debug] IOSApplication: View: Portrait 640x960
2015-05-18 13:41:33.406 IOSLauncher[3958:116515] [debug] IOSGraphics: 640.0x960.0, 2.0
2015-05-18 13:41:33.462 IOSLauncher[3958:116515] [debug] IOSGraphics: Display: ppi=264, density=1.65
2015-05-18 13:41:33.528 IOSLauncher[3958:116545] 13:41:33.527 WARNING:   139: The default output device's sample rate was changed.
2015-05-18 13:41:33.545 IOSLauncher[3958:116539] 13:41:33.545 WARNING:   256: Audio device's sample rate changed. You may need to restart the simulator.
2015-05-18 13:41:34.128 IOSLauncher[3958:116515] [debug] IOSApplication: created
Unable to load sqlite_jni: java.lang.UnsatisfiedLinkError: Couldn't load sqlite_jni from loader java.lang.BootClassLoader[/Users/badlogic/Library/Developer/CoreSimulator/Devices/06084D91-6498-4D24-ABBC-F6D12A0F909F/data/Containers/Bundle/Application/ABC6B0E0-2843-4B56-A458-6CE5F716C314/IOSLauncher.app/lib/boot/robovm-rt.jar:/Users/badlogic/Library/Developer/CoreSimulator/Devices/06084D91-6498-4D24-ABBC-F6D12A0F909F/data/Containers/Bundle/Application/ABC6B0E0-2843-4B56-A458-6CE5F716C314/IOSLauncher.app/lib/boot/robovm-rt-sources.jar:/Users/badlogic/Library/Developer/CoreSimulator/Devices/06084D91-6498-4D24-ABBC-F6D12A0F909F/data/Containers/Bundle/Application/ABC6B0E0-2843-4B56-A458-6CE5F716C314/IOSLauncher.app/lib/boot/robovm-cacerts-full.jar]: findLibrary returned null
2015-05-18 13:41:34.195 IOSLauncher[3958:116515] [info] TEST: Test insert
2015-05-18 13:41:34.196 IOSLauncher[3958:116515] [info] TEST: Test select
2015-05-18 13:41:34.289 IOSLauncher[3958:116515] [debug] IOSApplication: resumed
```

Thanks a lot for reporting and providing a test project!
