### ISSUE TITLE
gradle-test-resources fails on first compile after project creation

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-idea#82]
Create a new project in IDEA and compile via a run configuration:

```
2015-06-17 15:20:18,103 [    723]   INFO - etbrains.jps.cmdline.BuildMain - Pre-loaded process ready in 724 ms
2015-06-17 15:20:27,493 [  10113]   INFO - .incremental.IncProjectBuilder - Building project; isRebuild:false; isMake:true parallel compilation:false
2015-06-17 15:20:27,502 [  10122]   INFO - r.api.ClassFilesIndicesBuilder - class files data index disabled
2015-06-17 15:20:27,544 [  10164]   INFO - .incremental.IncProjectBuilder - gradle-resources-test:untitled21: java.lang.NoClassDefFoundError: org/apache/tools/ant/util/ReaderInputStream
org.jetbrains.jps.incremental.ProjectBuildException: gradle-resources-test:untitled21: java.lang.NoClassDefFoundError: org/apache/tools/ant/util/ReaderInputStream
    at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:971)
    at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:840)
    at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:663)
    at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:370)
    at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:191)
    at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:137)
    at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:293)
    at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:124)
    at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:242)
    at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:41)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/tools/ant/util/ReaderInputStream
    at org.jetbrains.jps.gradle.compiler.GradleResourcesBuilder.build(GradleResourcesBuilder.java:103)
    at org.jetbrains.jps.gradle.compiler.GradleResourcesBuilder.build(GradleResourcesBuilder.java:42)
    at org.jetbrains.jps.incremental.IncProjectBuilder.buildTarget(IncProjectBuilder.java:906)
    at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:887)
    at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:945)
    ... 14 more
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.util.ReaderInputStream
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 19 more
2015-06-17 15:20:28,243 [      0]   INFO - etbrains.jps.cmdline.BuildMain - Build process started. Classpath: /Applications/IntelliJ IDEA 14 CE.app/Contents/lib/jps-launcher.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/lib/tools.jar:/Applications/IntelliJ IDEA 14 CE.app/Contents/lib/optimizedFileManager.jar:/Applications/IntelliJ IDEA 14 CE.app/Contents/lib/ecj-4.4.jar
2015-06-17 15:20:28,541 [    298]   INFO - etbrains.jps.cmdline.BuildMain - Connection to IDE established in 260 ms
2015-06-17 15:20:28,631 [    388]   INFO - jps.cmdline.JpsModelLoaderImpl - Loading model: project path = /Users/badlogic/workspaces/robovm-test/untitled21, global options path = /Users/badlogic/Library/Caches/IdeaIC14/plugins-sandbox/config/options
2015-06-17 15:20:28,984 [    741]   INFO - jps.cmdline.JpsModelLoaderImpl - Model loaded in 353 ms
2015-06-17 15:20:28,985 [    742]   INFO - jps.cmdline.JpsModelLoaderImpl - Project has 1 modules, 5 libraries
```

Reopening the project resolves the issue.

**Comment by badlogic** [comment]
See https://devnet.jetbrains.com/message/5546485#5546485

**Comment by zhishengzhang** [comment]
请看这个链接http://stackoverflow.com/questions/27978908/java-lang-noclassdeffounderror-org-apache-tools-ant-util-readerinputstream-vaad

**Comment by zhishengzhang** [comment]
Try

File > Invalidate Caches / Restart...

**Comment by dpinheiro2** [comment]
Try a Gradle's newer version.
