### ISSUE TITLE
Ensure the plugin works on Win/Linux with an warning that iOS compilation only works on Mac OS X

### ISSUE THREAD

**Issue by Dunemaster** [robovm/robovm-idea#86]
RoboVM Idea plugin crashes on windows
Idea Community 14.1
RoboVM plugin 1.4

2015-06-19 13:12:24,551 [ 764673]   INFO - org.jetbrains.io.BuiltInServer - web server stopped 
2015-06-19 13:12:24,551 [ 764673]   INFO - Types.impl.FileTypeManagerImpl - FileTypeManager: 2 auto-detected files
Elapsed time on auto-detect: 2 ms 
2015-06-19 13:12:24,565 [ 764687]   INFO - dea.ddms.adb.AdbService$Ddmlib - DDMLib terminated 
2015-06-19 13:12:24,565 [ 764687]   INFO - il.indexing.FileBasedIndexImpl - START INDEX SHUTDOWN 
2015-06-19 13:12:24,586 [ 764708]   INFO - il.indexing.FileBasedIndexImpl - END INDEX SHUTDOWN 
2015-06-19 13:12:24,586 [ 764708]   INFO - stubs.SerializationManagerImpl - START StubSerializationManager SHUTDOWN 
2015-06-19 13:12:24,586 [ 764708]   INFO - stubs.SerializationManagerImpl - END StubSerializationManager SHUTDOWN 
2015-06-19 13:12:24,654 [ 764776]   WARN - api.vfs.impl.local.FileWatcher - Watcher terminated with exit code 0 
2015-06-19 13:12:24,654 [ 764776]   INFO - newvfs.persistent.PersistentFS - VFS dispose started 
2015-06-19 13:12:24,657 [ 764779]   INFO - newvfs.persistent.PersistentFS - VFS dispose completed 
2015-06-19 13:12:24,659 [ 764781]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------ 
2015-06-19 13:12:27,264 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2015-06-19 13:12:27,342 [     78]   INFO -        #com.intellij.idea.Main - IDE: IntelliJ IDEA (build #IC-141.1010.3, 12 May 2015 00:00) 
2015-06-19 13:12:27,342 [     78]   INFO -        #com.intellij.idea.Main - OS: Windows 8 (6.2, x86) 
2015-06-19 13:12:27,342 [     78]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_40-b26 (Oracle Corporation) 
2015-06-19 13:12:27,342 [     78]   INFO -        #com.intellij.idea.Main - JVM: 25.40-b25 (Java HotSpot(TM) Server VM) 
2015-06-19 13:12:27,342 [     78]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms128m -Xmx512m -XX:MaxPermSize=250m -XX:ReservedCodeCacheSize=150m -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -Djb.vmOptions=D:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1.3\bin\idea.exe.vmoptions -Xbootclasspath/a:D:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1.3\lib\boot.jar -Didea.paths.selector=IdeaIC14 
2015-06-19 13:12:27,389 [    125]   INFO -        #com.intellij.idea.Main - JNA library loaded (32-bit) in 47 ms 
2015-06-19 13:12:27,389 [    125]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational 
2015-06-19 13:12:27,389 [    125]   INFO -        #com.intellij.idea.Main - Using "FocusKiller" library to prevent focus stealing. 
2015-06-19 13:12:28,654 [   1390]   INFO - llij.ide.plugins.PluginManager - 30 plugins initialized in 437 ms 
2015-06-19 13:12:28,670 [   1406]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: Android Support (10.1.1.0), Ant Support (1.0), Bytecode Viewer (0.1), Copyright (8.1), Coverage, EditorConfig (1.0), Git Integration (8.1), GitHub, Gradle, Groovy (9.0), I18n for Java, IDEA CORE, IntelliLang (8.0), JUnit (1.0), Java Bytecode Decompiler (0.1), JavaFX (1.0), Maven Integration, Properties Support, Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), TestNG-J (8.0), XPathView + XSLT Support (4), XSLT-Debugger (1.4) 
2015-06-19 13:12:28,670 [   1406]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: RoboVM Intellij IDEA Plugin (1.4.0) 
2015-06-19 13:12:28,670 [   1406]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: CVS Integration (11), Eclipse Integration (3.0), Plugin DevKit (1.0), UI Designer, hg4idea (10.0) 
2015-06-19 13:12:29,076 [   1812]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=200; buffer=10; max=498008064 
2015-06-19 13:12:29,107 [   1843]   INFO - api.vfs.impl.local.FileWatcher - Starting file watcher: D:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1.3\bin\fsnotifier.exe 
2015-06-19 13:12:29,107 [   1843]   INFO - api.vfs.impl.local.FileWatcher - Native file watcher is operational. 
2015-06-19 13:12:29,448 [   2184]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: [] 
2015-06-19 13:12:29,698 [   2434]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2015-06-19 13:12:29,776 [   2512]   INFO - il.indexing.FileBasedIndexImpl - Version has changed for index filetypes. The index will be rebuilt. 
2015-06-19 13:12:30,136 [   2872]   INFO -                  TestNG Runner - Create TestNG Template Configuration 
2015-06-19 13:12:30,182 [   2918]   INFO - ellij.project.impl.ProjectImpl - 20 project components initialized in 312 ms 
2015-06-19 13:12:30,182 [   2918]   INFO - le.impl.ModuleManagerComponent - 0 module(s) loaded in 0 ms 
2015-06-19 13:12:30,464 [   3200]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Native library for windows-x86 not found
 [Plugin: org.robovm.intellij] 

java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Native library for windows-x86 not found [Plugin: org.robovm.intellij]
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:178)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Native library for windows-x86 not found [Plugin: org.robovm.intellij]
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:245)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:39)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:590)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:354)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:116)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    ... 16 more
Caused by: com.intellij.diagnostic.PluginException: Native library for windows-x86 not found [Plugin: org.robovm.intellij]
    ... 30 more
**Caused by: java.lang.UnsatisfiedLinkError: Native library for windows-x86 not found
    at org.robovm.llvm.NativeLibrary.load(NativeLibrary.java:75)
    at org.robovm.llvm.binding.LLVMJNI.<clinit>(LLVMJNI.java:802)
    at org.robovm.llvm.binding.LLVM.getLlvmHostTriple(LLVM.java:3103)
    at org.robovm.llvm.Target.<clinit>(Target.java:36)
    at org.robovm.compiler.config.OS.getDefaultOS(OS.java:51)
    at org.robovm.idea.components.RoboVmApplicationComponent.displaySetupWizard(RoboVmApplicationComponent.java:63)
    at org.robovm.idea.components.RoboVmApplicationComponent.initComponent(RoboVmApplicationComponent.java:43)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:568)
    ... 27 more**

**Comment by badlogic** [comment]
Thanks for reporting. RoboVM is currently targeted at Mac OS X as a
development environment. We should hover gracefully handle other OS.

**Comment by Dunemaster** [comment]
I understand, I do my development under MacOS, but sometimes I need to open the project under windows

**Comment by badlogic** [comment]
If your project uses Maven or Gradle, you don't need to install the RoboVM
plugin on Windows. The dependency management system will pull in the
appropriate RoboVM jars. We still shouldn't crash obviously :)

**Comment by Dunemaster** [comment]
Thanks!
But still I would need to specify some other JDK
It is a minor inconvinience, though

**Comment by badlogic** [comment]
That's a very good point that didn't occur to me. I'll try to fix up the
IDEA and possibly Eclipse plugin accordingly. Please keep this kind of
feedback coming, super valuable!

**Comment by badlogic** [comment]
This should be fixed now. The IDEA plugin will work on Windows and Linux, but obviously won't support opening storyboard files or compiling for iOS.
