### ISSUE TITLE
window with id="RoboVM" isn't registered

### ISSUE THREAD

**Issue by fechy** [robovm/robovm-idea#88]
After updating IntelliJ to the latest build (14.1.4) Im getting the following error.

``` java
window with id="RoboVM" isn't registered
java.lang.IllegalStateException: window with id="RoboVM" isn't registered
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.checkId(ToolWindowManagerImpl.java:791)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.notifyByBalloon(ToolWindowManagerImpl.java:1401)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.notifyByBalloon(ToolWindowManagerImpl.java:1392)
    at org.robovm.idea.RoboVmPlugin$1.run(RoboVmPlugin.java:88)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2350)
    at org.robovm.idea.RoboVmPlugin.logBalloon(RoboVmPlugin.java:84)
    at org.robovm.idea.RoboVmPlugin.logErrorThrowable(RoboVmPlugin.java:107)
    at org.robovm.idea.compilation.RoboVmCompileTask.loadConfig(RoboVmCompileTask.java:350)
    at org.robovm.idea.RoboVmPlugin.getModuleResourcePaths(RoboVmPlugin.java:443)
    at org.robovm.idea.interfacebuilder.IBIntegratorManager.moduleChanged(IBIntegratorManager.java:103)
    at org.robovm.idea.interfacebuilder.IBIntegratorModuleComponent.moduleAdded(IBIntegratorModuleComponent.java:51)
    at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:227)
    at com.intellij.openapi.module.impl.ModuleManagerImpl$5.run(ModuleManagerImpl.java:587)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
    at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAddedInWriteAction(ModuleManagerImpl.java:584)
    at com.intellij.openapi.module.impl.ModuleManagerComponent$3$1.run(ModuleManagerComponent.java:139)
    at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:161)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:699)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:818)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:197)
    at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:633)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:363)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:240)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:193)
    at com.intellij.openapi.module.impl.ModuleManagerComponent.fireModulesAdded(ModuleManagerComponent.java:155)
    at com.intellij.openapi.module.impl.ModuleManagerImpl.projectOpened(ModuleManagerImpl.java:572)
    at com.intellij.openapi.project.impl.ProjectImpl.projectOpened(ProjectImpl.java:385)
    at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:73)
    at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:420)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$3.projectOpened(ProjectManagerImpl.java:154)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:938)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:461)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:562)
    at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:182)
    at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:46)
    at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:357)
    at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:384)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:322)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:309)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:288)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
    at com.sun.proxy.$Proxy54.appStarting(Unknown Source)
    at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:328)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:699)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

I have the latest Robovm plugin (1.4.0), I'm using a trial license still valid, and I'm running it on a Mac with Yosemite.

This happens all the time I open IntelliJ.

Let me know if you need more info.

Thanks

**Comment by badlogic** [comment]
Thanks for reporting, will fix this until the next release next week.

**Comment by badlogic** [comment]
One question: do you have multiple IDEA windows open?

**Comment by fechy** [comment]
Hi Mario, 

No, only one window open. It happens on startup.

I've also noticed that neither run or debug works from the IDE as the heap memory is always reached and it fails. From command line it works perfectly. Dunno if can be of any help.

**Comment by badlogic** [comment]
How much heap memory did you give IDEA? See the getting started guide on
how to increase it. We recommend 2G, 1G should work as well though.
http://docs.robovm.com/getting-started/intellij.html

On Wed, Jul 1, 2015 at 3:11 PM, Fernando Giovanini <notifications@github.com

**Comment by badlogic** [comment]
I commited a fix for this. Please try the next nightly of the RoboVM IDEA plugin, available at http://download.robovm.org/. Go by the timestamp, it should be ready in an hour or two from now.

Please open a separate issue if run/debug does not work for you, including your heap memory settings.

Thanks for reporting!
