### ISSUE TITLE
Stepping into native/Bro methods throws exception

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-idea#91]
Currently observed in RoboVM Studio based on IDEA 15 EPA, testing with IDEA 14.

**Comment by badlogic** [comment]
It appears to be an issue with the Kotlin plugin:

```
Location with invalid code index
java.lang.InternalError: Location with invalid code index
    at com.sun.tools.jdi.ConcreteMethodImpl.codeIndexToLineInfo(ConcreteMethodImpl.java:182)
    at com.sun.tools.jdi.LocationImpl.getBaseLineInfo(LocationImpl.java:126)
    at com.sun.tools.jdi.LocationImpl.getLineInfo(LocationImpl.java:140)
    at com.sun.tools.jdi.LocationImpl.sourceName(LocationImpl.java:191)
    at com.sun.tools.jdi.LocationImpl.sourceName(LocationImpl.java:186)
    at com.sun.tools.jdi.LocationImpl.sourceName(LocationImpl.java:181)
    at org.jetbrains.kotlin.idea.debugger.JetPositionManager.getPsiFileByLocation(JetPositionManager.kt:141)
    at org.jetbrains.kotlin.idea.debugger.JetPositionManager.getSourcePosition(JetPositionManager.kt:78)
    at com.intellij.debugger.engine.CompoundPositionManager$1.process(CompoundPositionManager.java:92)
    at com.intellij.debugger.engine.CompoundPositionManager$1.process(CompoundPositionManager.java:89)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:70)
    at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:89)
    at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
    at com.intellij.debugger.ui.impl.watch.StackFrameDescriptorImpl$1.run(StackFrameDescriptorImpl.java:86)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:939)
    at com.intellij.debugger.ui.impl.watch.StackFrameDescriptorImpl.<init>(StackFrameDescriptorImpl.java:83)
    at com.intellij.debugger.engine.JavaStackFrame.<init>(JavaStackFrame.java:73)
    at com.intellij.debugger.engine.JavaExecutionStack$AppendFrameCommand.contextAction(JavaExecutionStack.java:169)
    at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:408)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by badlogic** [comment]
Fixed in debugger.
